# Generated by Django 6.1 on 2026-09-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_alter_note_id_note_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
